definitions:
  handlers.errorMsg:
    properties:
      message:
        type: string
    type: object
  handlers.getAllItemsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Item'
        type: array
    type: object
  handlers.getAllListsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.TodoList'
        type: array
    type: object
  handlers.responseId:
    properties:
      id:
        type: integer
    type: object
  handlers.signInInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.Item:
    properties:
      description:
        type: string
      done:
        type: boolean
      id:
        type: integer
      title:
        type: string
    required:
    - description
    - done
    - title
    type: object
  models.TodoList:
    properties:
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    required:
    - description
    - title
    type: object
  models.User:
    properties:
      name:
        type: string
      password:
        description: Not hash for a while
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/lists:
    get:
      consumes:
      - application/json
      description: get all lists
      operationId: get-all-lists
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.getAllListsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Get All Lists
      tags:
      - lists
    post:
      consumes:
      - application/json
      description: create todo list
      operationId: create-list
      parameters:
      - description: list info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.TodoList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Create todo list
      tags:
      - lists
  /api/lists/{id}:
    delete:
      consumes:
      - application/json
      description: delete list by id
      operationId: delete-list
      parameters:
      - description: list id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Delete list
      tags:
      - lists
    get:
      consumes:
      - application/json
      description: get list by id
      operationId: get-list-by-id
      parameters:
      - description: list id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TodoList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Get List By Id
      tags:
      - lists
    put:
      consumes:
      - application/json
      description: update list by id
      operationId: update-list
      parameters:
      - description: list id
        in: path
        name: id
        required: true
        type: integer
      - description: update list info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.TodoList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Update list
      tags:
      - lists
  /api/lists/{listId}/items:
    post:
      consumes:
      - application/json
      description: create item
      operationId: create-item
      parameters:
      - description: list id
        in: path
        name: listId
        required: true
        type: integer
      - description: Item
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Create item
      tags:
      - item
  /api/lists/{listId}/items/:
    get:
      consumes:
      - application/json
      description: Get all items
      operationId: get-all-items
      parameters:
      - description: list id
        in: path
        name: listId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.getAllItemsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Get all items
      tags:
      - item
  /api/lists/{listId}/items/{itemId}:
    delete:
      consumes:
      - application/json
      description: Delete item by id
      operationId: delete-item-by-id
      parameters:
      - description: list id
        in: path
        name: listId
        required: true
        type: integer
      - description: item id
        in: path
        name: itemId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Delete item by id
      tags:
      - item
    get:
      consumes:
      - application/json
      description: Get item by id
      operationId: get-item-by-id
      parameters:
      - description: list id
        in: path
        name: listId
        required: true
        type: integer
      - description: item id
        in: path
        name: itemId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Get item by id
      tags:
      - item
    put:
      consumes:
      - application/json
      description: Update item by id
      operationId: update-item-by-id
      parameters:
      - description: list id
        in: path
        name: listId
        required: true
        type: integer
      - description: item id
        in: path
        name: itemId
        required: true
        type: integer
      - description: Item content
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.responseId'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      security:
      - ApiKeyAuth: []
      summary: Update item by id
      tags:
      - item
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: sign in to account
      operationId: sign-in
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.errorMsg'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handlers.errorMsg'
      summary: SignUp
      tags:
      - auth
swagger: "2.0"
